---
collections:
  - name: community.general
    version: 12.1.0
  - name: community.docker
    version: 5.0.4
  - name: ansible.posix
    version: 2.1.0

roles:
  - src: gantsign.default-web-browser
    version: 4.0.0
  - src: danielrolls.nix
    version: v3.45.0
  - src: Oefenweb.ssh_keys
    version: v5.0.5
  - src: alvistack.flatpak
    version: 11.9.2
